### PR TITLE
setting the correct permissions of the ssh-config secret

### PR DESCRIPTION
**Pull request by KurtStam**

### CODE REVIEW

**Comment by KurtStam** [comment]
[merge]

**Comment by iocanel** [comment]
@KurtStam: This doesn't seem to be merged. I think you need to do it manually in this project.

**Comment by rawlingsj** [comment]
FWIW we're moving to jenkins2 and not using post start scripts anymore, we can use initcontainers to do the chmod instead

**Comment by KurtStam** [comment]
@rawlingsj it's in the start.sh, not the postStart.sh but I got your point. 

BTW it looks like initcontainer is supported as of openshift 3.3 and we are on 3.1. So we can use it soon  but not yet.

**Pull request merged**
